### ISSUE TITLE
Definir conteúdo necessário para: 

### ISSUE THREAD

**Issue by SouzaDaniel** [SouzaDaniel/DevWebGeografia#1]
- [x] Fontes de energia
- [x] Cada fonte de energia
- [x] Sustentabilidade
- [x] Planejamento do município (espaço e zona urbana a ser empregado)
- [x] Serviços do município (segurança, lazer, atendimento hospitalar, industria, mobilidade e saneamento)
- [x] Composição da tela sobre
- [x] Necessidade ou não de um portal informativo (notícias)

Todas essas metas devem ser concluídas até domingo (03) a noite, tudo que for analisado e optado deverá constar no relatório existente na pasta "Relatórios" localizado no drive da equipe de desenvolvimento.

Metas dedicadas a:
@Sn4k3rx
@Cast20 
@Amy2207

**Comment by Cast20** [comment]
A gente tentou
